server:
    port: 12000

spring:
    application:
        name: gulimall-search
    cloud:
        nacos:
            discovery:
                server-addr: 47.95.202.144:8848

    thymeleaf:
        cache: false


logging:
    level:
        com.bigdata.gulimall.search: debug
        root: warn
    pattern:
        console: "%d{yyyy-MM-dd} [%thread] - %msg%n"
