server:
  port: 12000

spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 47.95.202.144:8848
    alicloud:
      access-key: LTAI4GH1zUFBLN6WBsQVmMXS
      secret-key: tLcN62LFw5g67AKXPi1mxmrOKl35G3
      oss:
        endpoint: gulimall-mfljw.oss-cn-beijing.aliyuncs.com

  thymeleaf:
    cache: false


logging:
  level:
    com.bigdata.gulimall.search: debug
    root: warn
  pattern:
    console: "%d{yyyy-MM-dd} [%thread] - %msg%n"
